123-feat/mperez
dlab-team/c18-backend pull request #31
Opened 2024-05-30 01:21 UTC by manu4970

# Plantilla de Pull Request

## Descripción
Se crea endpoint /activar para cambiar el rol de los usuarios de inactivo a user, para esto tambien fue necesario crear un middleware para invalidar tokens usados en la activacion

## Cambios probados
Se pueba flujo de activacion por postman

## Comentarios adicionales
Se actualiza seeders de usuarios para que algunes tengan el rol inactivo

## Comprobaciones previas a la fusión
- [ ] Los cambios introducidos pasan todas las pruebas.
- [ ] Se ha revisado y se han resuelto los comentarios de los revisores.
- [ ] Se han actualizado los documentos relevantes si es necesario.
- [ ] La rama de esta solicitud de extracción se puede fusionar de manera segura.

2024-05-31 03:43 UTC, lfazocar requested changes
Solamente un pequeño detalle al momento de procesar el token.
También me llamó la atención q al de activar la cuenta responde con HTTP 501 (Not Implemented). En mi opinión debería responder con HTTP 204 (No Content)

2024-05-31 03:43 UTC, lfazocar commented on src/controllers/autenticacionController.js
> +    res.status(501).end();
```suggestion
    res.status(204).end();
```

2024-05-31 03:43 UTC, lfazocar commented on src/middleware/auth.js
> +    const token = req.header("Authorization");
```suggestion
    const token = req.headers.authorization.split(' ')[1];
```
Formato token en header:
```js
// req.headers
{
  ...
  authorization: 'Bearer header.payload.signature',
  ...
}
```

2024-05-31 03:49 UTC, diegorojas89z commented on src/middleware/auth.js
> +    const token = req.header("Authorization");
@lfazocar Una consulta, autenticacion.routes.js las rutas habría que modificar algo por lo del fix al middleware?

2024-05-31 03:57 UTC, lfazocar commented on src/middleware/auth.js
> +    const token = req.header("Authorization");
no, no es necesario
el problema estaba en /routes/index.js

2024-06-01 01:12 UTC, lfazocar approved these changes
Se ve bien 👍.
Lo único que me causa duda es que después de activar la cuenta el server envía HTTP 200 con los datos del usuario, no se si será mejor mandar un HTTP 204 en su lugar?

2024-06-01 01:14 UTC, merged