feat: Creación del Proyecto Base de Backend
dlab-team/c18-backend pull request #5
Opened 2024-03-21 20:20 UTC by jonathanriffo27

# Plantilla de Pull Request

## Descripción
Creación del Proyecto Base de Backend

## Problema
[Describe el problema o la necesidad que aborda esta solicitud de extracción. Incluye enlaces a problemas o incidencias relacionadas si es necesario.]

## Solución propuesta
[Explica cómo abordas el problema. Proporciona detalles sobre los cambios específicos que has realizado.]

## Capturas de pantalla (si es aplicable)
[Si los cambios afectan la interfaz de usuario, incluye capturas de pantalla que muestren antes y después de tus modificaciones.]

## Cambios probados
[Indica cómo has probado tus cambios. Incluye detalles sobre el entorno de prueba y las pruebas realizadas, como pruebas unitarias, pruebas de integración, etc.]

## Instrucciones para revisores
Una ves tenga docker instalado correr el siguiente comando:
docker-compose up -d
Encaso de hacer cambios al proyecto correr el siguiente comando:
docker-compose up --build -d

## Comentarios adicionales
[Agrega cualquier comentario adicional que consideres relevante, como dependencias de esta solicitud de extracción en otras tareas o cualquier otro contexto relevante.]

## Tareas pendientes
Pendientes lo siguiente:
- Configurar archivo .nvmrc para especificar la versión de Node.js.
- Configurar ESLint para garantizar la consistencia y calidad del código.
- Configurar Prettier para el formateo automático del código según las convenciones establecidas.

## Comprobaciones previas a la fusión
- [ ] Los cambios introducidos pasan todas las pruebas.
- [ ] Se ha revisado y se han resuelto los comentarios de los revisores.
- [ ] Se han actualizado los documentos relevantes si es necesario.
- [ ] La rama de esta solicitud de extracción se puede fusionar de manera segura.

## Referencias
[Si hay alguna referencia relacionada, como enlaces a documentación, artículos, o discusiones relevantes, agrégalas aquí.]

2024-03-22 20:45 UTC, NatSama2 submitted a review, later dismissed

2024-03-25 16:34 UTC, ejbogantes requested changes
En general todo está muy bien. Les dejé algunos comentarios y agreguen un .env.sample para saber cuales son las variables que necesitamos para correr el proyecto. Además de actualizar el README con las instrucciones necesarias para correr el proyecto.

2024-03-25 16:34 UTC, ejbogantes commented on package.json
Acá agreguemos los authors, listar con nombre y correo electrónico de todos los miembros del equipo de BE. Además, agregar el repositorio de GitHub

2024-03-25 16:34 UTC, ejbogantes commented on src/index.js
> +    console.log("Database connected");
Para los logs, utilicemos una herramienta como Winston o similar. [https://github.com/winstonjs/winston](https://github.com/winstonjs/winston ). Tenemos más opciones de formato.

2024-03-25 16:34 UTC, ejbogantes commented on .nvmrc
Acá agreguemos la última versión LTS de Node.js, la cual es 20.11.1

2024-03-25 16:34 UTC, ejbogantes commented on package.json
> +  "main": "index.js",
Agreguemos una validación de la versión de NPM y Node.js (v20.11.1)

2024-03-27 02:44 UTC, jonathanriffo27 commented
@ejbogantes  realice los cambios solicitados me falto agregar la validacion de npm y node

2024-03-28 01:29 UTC, NatSama2 approved these changes

2024-04-02 00:28 UTC, NatSama2 approved these changes

2024-04-16 23:23 UTC, ejbogantes approved these changes

2024-04-17 00:44 UTC, merged